# Generated by Django 3.2 on 2021-10-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211028_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_confirmed',
        ),
        migrations.DeleteModel(
            name='ConfirmString',
        ),
    ]
