# Generated by Django 3.2 on 2021-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20211028_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=2083)),
                ('grade', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
