# Generated by Django 3.2 on 2021-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='booking_url',
            field=models.CharField(default='abc', max_length=2083),
        ),
    ]
