# Generated by Django 3.2 on 2021-11-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.CharField(max_length=2083),
        ),
    ]
